// Generated by ReluxScript compiler
// Do not edit manually
// NOTE: SWC plugins require nightly Rust

use swc_common::{Span, DUMMY_SP, SyntaxContext};
use swc_ecma_ast::*;
use swc_ecma_visit::{Visit, VisitMut, VisitMutWith, VisitWith};

pub struct TestTsTypes {
    output: String,
    indent_level: usize,
    output: String,
}

impl Visit for TestTsTypes {}

impl TestTsTypes {
    pub fn new() -> Self {
        Self {
            output: String::new(),
            indent_level: 0,
            output: Default::default(),
        }
    }
    
    fn append(&mut self, s: &str) {
        self.output.push_str(s);
    }
    
    fn append_line(&mut self, s: &str) {
        for _ in 0..self.indent_level {
            self.output.push_str("    ");
        }
        self.output.push_str(s);
        self.output.push('\n');
    }
    
    fn indent(&mut self) {
        self.indent_level += 1;
    }
    
    fn dedent(&mut self) {
        if self.indent_level > 0 {
            self.indent_level -= 1;
        }
    }
    
    fn newline(&mut self) {
        self.output.push('\n');
    }
    
    pub fn to_string(&self) -> String {
        self.output.clone()
    }
    
    fn visit_mut_fn_decl(&mut self, node: &FnDecl) {
        match node.return_type {
            Some(type_ann) => {
                match type_ann.type_annotation {
                    TsType::TsKeywordType => {
                        {
                            self.output = "string"
                        }
                    }
                    TsType::TsKeywordType => {
                        {
                            self.output = "number"
                        }
                    }
                    TsType::TsKeywordType => {
                        {
                            self.output = "boolean"
                        }
                    }
                    TsType::TsArrayType(array_type) => {
                        {
                            self.output = "array"
                        }
                    }
                    _ => {
                        {
                            self.output = "other"
                        }
                    }
                }
            }
            _ => {}
        }
    }
    
    // Exit-hook
    pub fn finish() -> String {
        self.output
    }
    
}
