// Generated by ReluxScript compiler
// Do not edit manually

module.exports = function({ types: t }) {
  
  class Template {
  constructor(path, bindings) {
      this.path = path;
      this.bindings = bindings;
    }
  }
  
  function test_hashmap_basic() {
    let map = HashMap.new();
    map.splice("key1", 0, "value1");
    map.splice("key2", 0, "value2");
    const value = map.get("key1");
    if (map.contains_key("key1")) {
    }
    const count = map.length;
  }
  
  function test_hashset_basic() {
    let set = HashSet.new();
    set.insert("item1");
    set.insert("item2");
    if (set.includes("item1")) {
    }
    const count = set.length;
  }
  
  function test_iteration() {
    let map = HashMap.new();
    map.splice("a", 0, "1");
    map.splice("b", 0, "2");
    for (const key of map.keys()) {
      const k = key;
    }
    for (const value of map.values()) {
      const v = value;
    }
  }
  
  let state = {};
  
  return {
    visitor: {

    }
  };
};
