// Generated by ReluxScript compiler
// Do not edit manually

use swc_common::{Span, DUMMY_SP};
use swc_ecma_ast::*;
use swc_ecma_visit::{VisitMut, VisitMutWith};
use std::collections::{HashMap, HashSet};

#[derive(Debug, Clone)]
pub struct Template {
    pub path: String,
    pub bindings: Vec<String>,
}

pub struct HashMapHashSetTest {
    // Plugin state
}

impl HashMapHashSetTest {
    pub fn new() -> Self {
        Self {}
    }
    
    pub fn test_hashmap_basic() {
        let mut map = HashMap::new();
        map.insert("key1", "value1");
        map.insert("key2", "value2");
        let value = map.get(&"key1");
        if map.contains_key(&"key1") {
        }
        let count = map.len();
    }
    
    pub fn test_hashset_basic() {
        let mut set = HashSet::new();
        set.insert("item1");
        set.insert("item2");
        if set.contains(&"item1") {
        }
        let count = set.len();
    }
    
    pub fn test_iteration() {
        let mut map = HashMap::new();
        map.insert("a", "1");
        map.insert("b", "2");
        for key in map.keys() {
            let k = key.clone();
        }
        for value in map.values() {
            let v = value.clone();
        }
    }
}

impl VisitMut for HashMapHashSetTest {
}
