// Generated by ReluxScript compiler
// Do not edit manually

use swc_common::{Span, DUMMY_SP, SyntaxContext};
use swc_ecma_ast::*;
use swc_ecma_visit::{VisitMut, VisitMutWith, VisitWith};

#[derive(Clone, Debug)]
struct Stats {
    removed_count: i32,
}

pub struct ConsoleRemover {
}

impl VisitMut for ConsoleRemover {
    fn visit_mut_call_expr(&mut self, node: &mut CallExpr) {
        let callee = node.callee.clone();
        let args_count = node.args.len();
        if (args_count > 0) {
            for arg in node.args.clone() {
                let _temp = arg;
            }
        }
    }
    
    fn visit_mut_ident(&mut self, node: &mut Ident) {
        let name = node.sym.to_string();
        if (name == "oldName") {
            *node = Ident { sym: "newName".into(), span: DUMMY_SP, optional: false, ctxt: SyntaxContext::empty() }.into()
        }
    }
    
}

fn is_console_method(name: &String) -> bool {
    return (((name == "log") || (name == "warn")) || (name == "error"));
}

