// Generated by ReluxScript compiler
// Do not edit manually

module.exports = function({ types: t }) {
  
  function safe_get_name(node) {
    const prop = node.property;
    const name = prop.name;
    return name;
  }
  
  function regular_get_name(node) {
    const __property_1 = node.property;
    let name = undefined;
    if ((t.isIdentifier(__property_1))) {
      name = __property_1.name;
    } else {
      throw new Error("Expected Ident for .name access");
    }
    return name;
  }
  
  let state = {};
  
  return {
    visitor: {

    }
  };
};
