// Generated by ReluxScript compiler
// Do not edit manually

module.exports = function({ types: t }) {
  
  function test_array_pattern_elements(pat) {
    for (const elem of pat.elements) {
      const __iflet_3 = elem;
      if (__iflet_3 !== null && __iflet_3 !== undefined) {
        const p = __iflet_3;
        if ((t.isIdentifier(p))) {
          const name = p.name;
        }
      }
    }
  }
  
  function extract_use_state(decl) {
    if ((t.isArrayPattern(decl.id))) {
      const arr = decl.id;
      if ((arr.elements.length > 0)) {
        const first_elem = arr.elements[0];
        const __iflet_4 = first_elem;
        if (__iflet_4 !== null && __iflet_4 !== undefined) {
          const pat = __iflet_4;
          if ((t.isIdentifier(pat))) {
            const state_var = pat.name;
          }
        }
      }
      if ((arr.elements.length > 1)) {
        const second_elem = arr.elements[1];
        const __iflet_4 = second_elem;
        if (__iflet_4 !== null && __iflet_4 !== undefined) {
          const pat = __iflet_4;
          if ((t.isIdentifier(pat))) {
            const setter_var = pat.name;
          }
        }
      }
    }
  }
  
  function test_call_args(call) {
    for (const arg of call.arguments) {
      const expr = arg.expr;
      if ((t.isStringLiteral(expr))) {
        const value = expr.value;
      }
    }
  }
  
  function extract_initial_value(call) {
    if ((call.arguments.length > 0)) {
      const first_arg = call.arguments[0];
      const expr = first_arg.expr;
      if ((t.isStringLiteral(expr))) {
        return expr.value;
      } else if ((t.isNumericLiteral(expr))) {
        return expr.value;
      }
    }
    return "null";
  }
  
  function extract_effect_deps(call) {
    let deps = [];
    if ((call.arguments.length > 1)) {
      const deps_arg = call.arguments[1];
      const expr = deps_arg.expr;
      if ((t.isArrayExpression(expr))) {
        for (const elem of expr.elements) {
          const __iflet_5 = elem;
          if (__iflet_5 !== null && __iflet_5 !== undefined) {
            const item = __iflet_5;
            const inner_expr = item.expr;
            if ((t.isIdentifier(inner_expr))) {
              deps.push(inner_expr.name);
            }
          }
        }
      }
    }
    return deps;
  }
  
  let state = {};
  
  return {
    visitor: {
      VariableDeclarator(path) {
        const node = path.node;
        const __iflet_4 = node.init;
        if (__iflet_4 !== null && __iflet_4 !== undefined) {
          const init = __iflet_4;
          if ((t.isCallExpression(init))) {
            if ((t.isIdentifier(init.callee))) {
              const callee_name = init.callee.name;
              if ((callee_name === "useState")) {
                if ((t.isArrayPattern(node.id))) {
                  const arr = node.id;
                  if ((arr.elements.length > 0)) {
                    const __iflet_10 = arr.elements[0];
                    if (__iflet_10 !== null && __iflet_10 !== undefined) {
                      const pat = __iflet_10;
                      if ((t.isIdentifier(pat))) {
                        const state_name = pat.name;
                      }
                    }
                  }
                  if ((init.arguments.length > 0)) {
                    const arg = init.arguments[0];
                    const value_expr = arg.expr;
                  }
                }
              }
            }
          }
        }
      }
    }
  };
};
