// Generated by ReluxScript compiler
// Do not edit manually

use swc_common::{Span, DUMMY_SP};
use swc_ecma_ast::*;
use swc_ecma_visit::{VisitMut, VisitMutWith};

pub struct FieldTypesTest {
    // Plugin state
}

impl FieldTypesTest {
    pub fn new() -> Self {
        Self {}
    }
    
    pub fn test_array_pattern_elements(pat: &ArrayPat) {
        for elem in &pat.elems {
            if let Some(p) = elem {
                if let Pat::Ident(p) = &p {
                    let name = p.id.sym.clone();
                }
            }
        }
    }
    
    pub fn extract_use_state(decl: &VariableDeclarator) {
        if let Pat::Array(id) = &decl.name {
            let arr = decl.name.clone();
            if (arr.elems.len() > 0) {
                let first_elem = &arr.elems[0];
                if let Some(pat) = first_elem {
                    if let Pat::Ident(pat) = &pat {
                        let state_var = pat.id.sym.clone();
                    }
                }
            }
            if (arr.elems.len() > 1) {
                let second_elem = &arr.elems[1];
                if let Some(pat) = second_elem {
                    if let Pat::Ident(pat) = &pat {
                        let setter_var = pat.id.sym.clone();
                    }
                }
            }
        }
    }
    
    pub fn test_call_args(call: &CallExpr) {
        for arg in &call.args {
            let expr = &arg.expr;
            if let Expr::Lit(Lit::Str(expr)) = &expr {
                let value = expr.value.clone();
            }
        }
    }
    
    pub fn extract_initial_value(call: &CallExpr) -> String {
        if (call.args.len() > 0) {
            let first_arg = &call.args[0];
            let expr = &first_arg.expr;
            if let Expr::Lit(Lit::Str(expr)) = &expr {
                return expr.value.clone();
            } else if let Expr::Lit(Lit::Num(expr)) = &expr {
                return expr.value.to_string();
            }
        }
        return "null";
    }
    
    pub fn extract_effect_deps(call: &CallExpr) -> Vec<String> {
        let mut deps = vec![];
        if (call.args.len() > 1) {
            let deps_arg = &call.args[1];
            let expr = &deps_arg.expr;
            if let Expr::Array(expr) = &expr {
                for elem in &expr.elems {
                    if let Some(item) = elem {
                        let inner_expr = &item.expr;
                        if let Expr::Ident(inner_expr) = &inner_expr {
                            deps.push(inner_expr.sym.clone());
                        }
                    }
                }
            }
        }
        return deps;
    }
}

impl VisitMut for FieldTypesTest {
    
    fn visit_mut_variable_declarator(&mut self, n: &mut VariableDeclarator) {
        if let Some(init) = &n.init {
            if let Expr::Call(init) = &init {
                if let Callee::Expr(callee) = &init.callee {
                    let callee_name = { let __callee = &init.callee; match __callee { Callee::Expr(e) => match e.as_ref() { Expr::Ident(i) => i.sym.clone(), _ => "".into() }, _ => "".into() } }.clone();
                    if (callee_name == "useState") {
                        if let Pat::Array(id) = &decl.name {
                            let arr = n.name.clone();
                            if (arr.elems.len() > 0) {
                                if let Some(pat) = &arr.elems[0] {
                                    if let Pat::Ident(pat) = &pat {
                                        let state_name = pat.id.sym.clone();
                                    }
                                }
                            }
                            if (init.args.len() > 0) {
                                let arg = &init.args[0];
                                let value_expr = &arg.expr;
                            }
                        }
                    }
                }
            }
        }
    }
}
