// Generated by ReluxScript compiler
// Do not edit manually

module.exports = function({ types: t }) {
  
  let state = {};
  
  return {
    visitor: {
      CallExpression(path) {
        const node = path.node;
        if ((t.isMemberExpression(node.callee) && t.isIdentifier(node.callee.object) && node.callee.object.name === "console" && t.isIdentifier(node.callee.property) && node.callee.property.name === "log")) {
          const x = 1;
        }
      }
    }
  };
};
