// Generated by ReluxScript compiler
// Do not edit manually

use swc_common::{Span, DUMMY_SP};
use swc_ecma_ast::*;
use swc_ecma_visit::{VisitMut, VisitMutWith};

pub struct BlockTest {
    // Plugin state
}

impl BlockTest {
    pub fn new() -> Self {
        Self {}
    }

    fn compute() -> i32 {
        let result = {
          let x = 5;
          let y = 10;
          (x + y);
        };
        result;
    }
}

impl VisitMut for BlockTest {
}
