// Generated by ReluxScript compiler
// Do not edit manually

module.exports = function({ types: t }) {

  function compute() {
    const result = (() => {
      const x = 5;
      const y = 10;
      (x + y);
    })();
    result;
  }

  let state = {};

  return {
    visitor: {

    }
  };
};
