// Generated by ReluxScript compiler
// Do not edit manually

module.exports = function({ types: t }) {

  function transform_items(items) {
    const result = [1, 2, 3];
    result.iter().map((item) => (() => {
      const doubled = (item * 2);
      doubled;
    })());
  }

  let state = {};

  return {
    visitor: {

    }
  };
};
