// Generated by ReluxScript compiler
// Do not edit manually

use swc_common::{Span, DUMMY_SP};
use swc_ecma_ast::*;
use swc_ecma_visit::{VisitMut, VisitMutWith};

pub struct ClosureTest {
    // Plugin state
}

impl ClosureTest {
    pub fn new() -> Self {
        Self {}
    }

    fn transform_items(items: Vec<Node>) {
        let result = vec![1, 2, 3];
        result.iter().map(|item| {
          let doubled = (item * 2);
          doubled;
        });
    }
}

impl VisitMut for ClosureTest {
}
