// Module imports
const babel = require('@babel/core');
const fs = require('fs');
const parser = {
  parse_file: (path) => {
    try {
      const code = fs.readFileSync(path, 'utf-8');
      const ast = babel.parseSync(code, {
        filename: path,
        presets: ['@babel/preset-typescript'],
        plugins: ['@babel/plugin-syntax-jsx'],
      });
      return { ok: true, value: ast };
    } catch (error) {
      return { ok: false, error: error.message };
    }
  },
  parse: (code) => {
    try {
      const ast = babel.parseSync(code, {
        presets: ['@babel/preset-typescript'],
        plugins: ['@babel/plugin-syntax-jsx'],
      });
      return { ok: true, value: ast };
    } catch (error) {
      return { ok: false, error: error.message };
    }
  },
  parse_with_syntax: (code, syntax) => {
    try {
      let options = {};
      if (syntax === 'TypeScript') {
        options = {
          presets: ['@babel/preset-typescript'],
          plugins: ['@babel/plugin-syntax-jsx'],
        };
      } else if (syntax === 'JSX') {
        options = {
          plugins: ['@babel/plugin-syntax-jsx'],
        };
      } else {
        options = {};
      }
      const ast = babel.parseSync(code, options);
      return { ok: true, value: ast };
    } catch (error) {
      return { ok: false, error: error.message };
    }
  },
};

// Generated by ReluxScript compiler
// Do not edit manually

module.exports = function({ types: t }) {

  function analyze_file(file_path) {
    const __result = parser.parse_file(file_path);
    if (!__result.ok) {
      return { ok: false, error: __result.error };
    }
    const ast = __result.value;
    return { ok: true, value: undefined };
  }

  function parse_code_snippet(code) {
    const __result = parser.parse(code);
    if (!__result.ok) {
      return { ok: false, error: __result.error };
    }
    const ast = __result.value;
    return { ok: true, value: undefined };
  }

  function parse_with_custom_syntax(code) {
    const __result = parser.parse_with_syntax(code, "TypeScript");
    if (!__result.ok) {
      return { ok: false, error: __result.error };
    }
    const ast = __result.value;
    return { ok: true, value: undefined };
  }

  let state = {};

  return {
    visitor: {

    }
  };
};
