// Generated by ReluxScript compiler
// Do not edit manually

module.exports = function({ types: t }) {

  // Pre-transformation hook

  function pre(file) {
    const original_code = file.code;
  }

  // Post-transformation hook

  function exit(program, state) {
    const output_path = "test.out";
  }

  let state = {};

  return {
    pre(file) {
      pre(file);
    },

    visitor: {
      Program: {
        exit(path, state) {
          exit(path.node, state);
        }
      },

      JSXElement(path) {
        const node = path.node;
      }
    }
  };
};
