// Generated by ReluxScript compiler
// Do not edit manually

use swc_common::{Span, DUMMY_SP};
use swc_ecma_ast::*;
use swc_ecma_visit::{VisitMut, VisitMutWith};

use swc_ecma_visit::Visit;

pub struct TestWriterHooks {
    output: String,
    indent_level: usize,
}

impl TestWriterHooks {
    pub fn new() -> Self {
        Self {
            output: String::new(),
            indent_level: 0,
        }
    }

    fn append(&mut self, s: &str) {
        self.output.push_str(s);
    }

    fn newline(&mut self) {
        self.output.push('\n');
    }

    fn indent(&mut self) {
        self.indent_level += 1;
    }

    fn dedent(&mut self) {
        self.indent_level -= 1;
    }

    /// Finalize output (from exit hook)
    pub fn finish(mut self) -> String {
        // Babel-only code omitted
        self.output
    }

    // Note: pre() hook not supported in SWC (no source access)

}

impl Visit for TestWriterHooks {

    fn visit_ident(&mut self, n: &Ident) {
        self.append(n.sym);
        self.append(" ");
    }
}
