// Generated by ReluxScript compiler
// Do not edit manually

module.exports = function({ types: t }) {
  const builder = {
    _output: [],
    _indentLevel: 0,
    append(s) { this._output.push(s); },
    newline() { this._output.push('\n'); },
    indent() { this._indentLevel++; },
    dedent() { this._indentLevel--; },
    toString() { return this._output.join(''); }
  };

  // Pre-hook

  function pre(file) {
    builder._filename = file.opts.filename || "unknown";
  }

  // Exit hook

  function exit(program, state, builder) {
    const output = builder.toString();
            state.file.metadata.collectedIdentifiers = output.trim();
  }

  return {
    pre(file) {
      pre(file);
    },

    visitor: {
      Program: {
        exit(path, state) {
          exit(path.node, state, builder);
        }
      },

      Identifier(path) {
        const node = path.node;
        builder.append(node.name);
        builder.append(" ");
      },
    }
  };
};
