// Generated by ReluxScript compiler
// Do not edit manually

use swc_common::{Span, DUMMY_SP};
use swc_ecma_ast::*;
use swc_ecma_visit::{VisitMut, VisitMutWith};

pub struct TestHooks {
    // Plugin state
}

impl TestHooks {
    pub fn new() -> Self {
        Self {}
    }
}

impl VisitMut for TestHooks {

    fn visit_mut_jsx_element(&mut self, n: &mut JSXElement) {
    }
}
