// Generated by ReluxScript compiler
// Do not edit manually

use swc_common::{Span, DUMMY_SP};
use swc_ecma_ast::*;
use swc_ecma_visit::{VisitMut, VisitMutWith};

pub struct TryTest {
    // Plugin state
}

impl TryTest {
    pub fn new() -> Self {
        Self {}
    }

    fn get_name(node: &Node) -> Result<String, String> {
        let id = node.id?;
        Ok(id.name);
    }
}

impl VisitMut for TryTest {
}
