// Generated by ReluxScript compiler
// Do not edit manually

module.exports = function({ types: t }) {

  function get_name(node) {
    const __result = node.id;
    if (!__result.ok) {
      return { ok: false, error: __result.error };
    }
    const id = __result.value;
    return { ok: true, value: id.name };
  }

  let state = {};

  return {
    visitor: {

    }
  };
};
