// Generated by ReluxScript compiler
// Do not edit manually

module.exports = function({ types: t }) {

  function unpack_values() {
    const data = [1, 2];
    const [x, y] = data;
    const result = (x + y);
  }

  let state = {};

  return {
    visitor: {

    }
  };
};
