// Generated by ReluxScript compiler
// Do not edit manually

use swc_common::{Span, DUMMY_SP};
use swc_ecma_ast::*;
use swc_ecma_visit::{VisitMut, VisitMutWith};

pub struct TupleTest {
    // Plugin state
}

impl TupleTest {
    pub fn new() -> Self {
        Self {}
    }

    fn unpack_values() {
        let data = vec![1, 2];
        let (x, y) = data;
        let result = (x + y);
    }
}

impl VisitMut for TupleTest {
}
