// Generated by ReluxScript compiler
// Do not edit manually

use swc_common::{Span, DUMMY_SP};
use swc_ecma_ast::*;
use swc_ecma_visit::{VisitMut, VisitMutWith};

pub struct UnitTest {
    // Plugin state
}

impl UnitTest {
    pub fn new() -> Self {
        Self {}
    }

    fn test_unit() {
        let x = ();
        Ok(());
    }
}

impl VisitMut for UnitTest {
}
