// Generated by ReluxScript compiler
// Do not edit manually

use swc_common::{Span, DUMMY_SP};
use swc_ecma_ast::*;
use swc_ecma_visit::{VisitMut, VisitMutWith};

pub struct ImplSimpleTest {
    // Plugin state
}

impl ImplSimpleTest {
    pub fn new() -> Self {
        Self {}
    }
}

impl VisitMut for ImplSimpleTest {
}
