// Generated by ReluxScript compiler
// Do not edit manually

module.exports = function({ types: t }) {
  
  function get_property_name(member) {
    const __property_1 = member.property;
    let name = undefined;
    if ((t.isIdentifier(__property_1))) {
      name = __property_1.name;
    } else {
      throw new Error("Expected Ident for .name access");
    }
    return name;
  }
  
  function get_property_name_safe(member) {
    const property = member.property;
    if ((t.isIdentifier(property))) {
      const name = property.name;
      return name;
    }
    return "unknown";
  }
  
  let state = {};
  
  return {
    visitor: {

    }
  };
};
