// Generated by ReluxScript compiler
// Do not edit manually

module.exports = function({ types: t }) {
  
  function analyze_all(node) {
    let count = 0;
    // Captures: [&mut count]
    const __nestedVisitor = {
      Identifier(path) {
        const id = path.node;
        count += 1;
      },
    };
    node.body.traverse(__nestedVisitor);
    return count;
  }
  
  let state = {};
  
  return {
    visitor: {
      Program(path) {
        const node = path.node;
        let count = 0;
        let total = 0;
        // Captures: [&mut count, &mut total]
        const __nestedVisitor = {
          Identifier(path) {
            const id = path.node;
            count += 1;
            total += 1;
          },
        };
        node.body.traverse(__nestedVisitor);
        return count;
      }
    }
  };
};
