// Generated by ReluxScript compiler
// Do not edit manually

use swc_common::{Span, DUMMY_SP};
use swc_ecma_ast::*;
use swc_ecma_visit::{VisitMut, VisitMutWith};

pub struct CapturingTest {
    // Plugin state
}

impl CapturingTest {
    pub fn new() -> Self {
        Self {}
    }
    
    pub fn analyze_all(node: &Program) -> i32 {
        let mut count = 0;
        let mut __visitor = __InlineVisitor_0 {
            count: &mut count,
        };
        node.body.visit_mut_with(&mut __visitor);
        return count;
    }
}

impl VisitMut for CapturingTest {
    
    fn visit_mut_program(&mut self, n: &mut Program) {
        let mut count = 0;
        let mut total = 0;
        let mut __visitor = __InlineVisitor_1 {
            count: &mut count,
            total: &mut total,
        };
        n.body.visit_mut_with(&mut __visitor);
        return count;
    }
}

// Hoisted inline visitors for traverse blocks
struct __InlineVisitor_0<'a> {
    count: &'a mut i32,
}

impl<'a> VisitMut for __InlineVisitor_0<'a> {
    fn visit_mut_identifier(&mut self, id: &mut Ident) {
        self.count += 1;
    }
}

struct __InlineVisitor_1<'a> {
    count: &'a mut i32,
    total: &'a mut i32,
}

impl<'a> VisitMut for __InlineVisitor_1<'a> {
    fn visit_mut_identifier(&mut self, id: &mut Ident) {
        self.count += 1;
        self.total += 1;
    }
}

